const test=require('node:test');const assert=require('node:assert/strict');const guest=require('../lib/pm-guest-billing.cjs');const handler=require('../api/pm-guest-bill.js');
const bill={id:'11111111-1111-4111-8111-111111111111',booking_id:'22222222-2222-4222-8222-222222222222',request_id:'33333333-3333-4333-8333-333333333333',property_manager_id:'44444444-4444-4444-8444-444444444444',revision:2,status:'ready',amount_due_cents:13500,checkout_attempt:0,snapshot:{manager_email:'manager@example.com',company_name:'Test PM',contact_name:'Manager',job_ref:'DD-TEST',address:'Test address',base_fee_cents:8000,full_service_cents:2000,parts_cost_cents:3500,total_cents:13500,collected_cents:0,approval_limit_cents:15000,parts_on_order:false},expires_at:new Date(Date.now()+86400000).toISOString()};
const booking={id:bill.booking_id,status:'billing_pending'};
const reply=data=>({ok:true,status:200,json:async()=>data});
async function mocked(fn,fetcher){const oldFetch=global.fetch;const names={SUPABASE_URL:'https://test.supabase.co',SUPABASE_SERVICE_ROLE_KEY:'test-secret',TOKEN_SIGNING_SECRET:'test-signing-secret',RESEND_API_KEY:'test-email',SITE_ORIGIN:'https://www.dryerdudes.com'};const prev={};for(const[k,v]of Object.entries(names)){prev[k]=process.env[k];process.env[k]=v;}global.fetch=fetcher || (()=>{throw Error('Unexpected request');});try{return await fn();}finally{global.fetch=oldFetch;for(const[k,v]of Object.entries(prev)){if(v===undefined)delete process.env[k];else process.env[k]=v;}}}
async function run(body,fetcher,headers={}){return mocked(async()=>{const result={};const res={setHeader(){},status(code){result.status=code;return this;},json(data){result.data=data;return this;}};await handler({method:'POST',headers,body},res);return result;},fetcher);}
test('secure links are signed for bill ID and revision; tampering cannot resolve a bill',()=>mocked(()=>{const token=guest.tokenFor(bill);assert.deepEqual(guest.verifyToken(token),{id:bill.id,revision:2});assert.throws(()=>guest.verifyToken(token.replace('.2.','.3.')));assert.throws(()=>guest.verifyToken('x'));}));
test('review exposes itemized bill but no manager email; does not create Stripe sessions',()=>mocked(async()=>{const view=await guest.getView(bill);assert.equal(view.invoice.manager_email,undefined);assert.equal(view.invoice.base_fee_cents,8000);assert.equal(view.invoice.amount_due_cents,13500);}));
test('old bill revisions are rejected',()=>mocked(async()=>{await assert.rejects(guest.loadBill(guest.tokenFor({...bill,revision:1})),/replaced/);},async()=>reply([bill])));
test('unapproved bills cannot create a Stripe checkout',()=>mocked(async()=>{let calls=0;await assert.rejects(guest.checkout({...bill,status:'pending_approval'},booking,{checkout:{sessions:{create(){calls++;}}}},guest.tokenFor(bill)),/approved/);assert.equal(calls,0);}));
const writes=[];
test('checkout charges exact remaining balance to manager; has no saved-card authorization',()=>mocked(async()=>{let params,options;const stripe={checkout:{sessions:{create:async(p,o)=>{params=p;options=o;return{id:'cs_test_guest',url:'https://checkout.stripe.com/test'};}}}};const r=await guest.checkout(bill,booking,stripe,guest.tokenFor(bill));assert.equal(r.checkout_url,'https://checkout.stripe.com/test');assert.equal(params.customer_email,'manager@example.com');assert.equal(params.line_items[0].price_data.unit_amount,13500);assert.deepEqual(params.payment_method_types,['card']);assert.equal(params.payment_intent_data.setup_future_usage,undefined);assert.equal(params.metadata.kind,'pm_guest_bill');assert.equal(params.metadata.guest_bill_revision,'2');assert(options.idempotencyKey.includes('/2/1'));assert(writes.some(x=>x.stripe_session_id==='cs_test_guest'));},async(_u,o)=>{const b=JSON.parse(o.body);writes.push(b);return reply([b]);}));
// Check database persistence separately from checkout parameters.
const sequence=[];
test('session is persisted before exposing its URL',()=>mocked(async()=>{const stripe={checkout:{sessions:{create:async()=>{sequence.push('create');return{id:'cs_test_guest',url:'https://checkout.stripe.com/test'};}}}};const result=await guest.checkout(bill,booking,stripe,guest.tokenFor(bill));sequence.push('return');assert.deepEqual(sequence,['attempt','create','session','billing','return']);assert.equal(result.ok,true);},async(u,o)=>{const b=JSON.parse(o.body);sequence.push(u.includes('booking_billing')?'billing':b.stripe_session_id?'session':'attempt');return reply([b]);}));
test('repeated pay click reuses an open checkout session',()=>mocked(async()=>{let creates=0;const stripe={checkout:{sessions:{retrieve:async()=>({status:'open',url:'https://checkout.stripe.com/existing'}),create(){creates++;}}}};const r=await guest.checkout({...bill,stripe_session_id:'cs_test_existing'},booking,stripe,guest.tokenFor(bill));assert.equal(r.checkout_url,'https://checkout.stripe.com/existing');assert.equal(creates,0);}));
const paid={id:'cs_test_guest',status:'complete',payment_status:'paid',mode:'payment',currency:'usd',amount_total:13500,payment_intent:'pi_test_guest',metadata:{kind:'pm_guest_bill',guest_bill_id:bill.id,guest_bill_revision:'2'}};
test('unpaid, wrong amount, stale revision and wrong session never reach settlement',()=>mocked(async()=>{for(const patch of [{payment_status:'unpaid'},{amount_total:13501},{currency:'eur'},{id:'cs_test_wrong'},{metadata:{...paid.metadata,guest_bill_revision:'1'}}])await assert.rejects(guest.settleSession({...bill,stripe_session_id:paid.id},{...paid,...patch}));}));
test('paid-session settlement uses transactional RPC and payment intent',()=>mocked(async()=>{const r=await guest.settleSession({...bill,stripe_session_id:paid.id},paid);assert.equal(r.duplicate,false);},async(u,o)=>{assert(u.endsWith('/rpc/record_pm_guest_bill_payment'));const p=JSON.parse(o.body);assert.equal(p.p_amount_cents,13500);assert.equal(p.p_payment_intent_id,'pi_test_guest');assert.equal(p.p_revision,2);return reply({duplicate:false});}));
test('approval is atomic and tied to bill revision and lease',()=>mocked(async()=>{const r=await guest.applyApproval({...bill,status:'pending_approval',lock_id:'lock'},booking,'approve');assert.equal(r.status,'ready');},async(u,o)=>{if(u.endsWith('/rpc/decide_pm_guest_bill')){const p=JSON.parse(o.body);assert.equal(p.p_approve,true);assert.equal(p.p_revision,2);assert.equal(p.p_lock_id,'lock');return reply({...bill,status:'ready'});}if(u==='https://api.resend.com/emails')return reply({id:'email'});throw Error(u);}));
test('submission expires old unpaid checkout before editing',()=>mocked(async()=>{const sequence=[];const stripe={checkout:{sessions:{retrieve:async()=>({status:'open'}),expire:async()=>{sequence.push('expire');}}}};let call=0;const oldFetch=global.fetch;global.fetch=async(u,o={})=>{if(o.method==='PATCH'){const b=JSON.parse(o.body);if(b.status==='editing')sequence.push('edit');return reply([{...bill,stripe_session_id:'cs_test_old',...b}]);}return reply([{...bill,stripe_session_id:'cs_test_old'}]);};try{const lease=await guest.beginSubmission({booking,request:{id:bill.request_id},context:{pm:{id:bill.property_manager_id}},stripe});assert.deepEqual(sequence,['expire','edit']);assert(lease.lock_id);}finally{global.fetch=oldFetch;}}));
test('paid bill cannot be resubmitted or billed twice',()=>mocked(async()=>{await assert.rejects(guest.beginSubmission({booking,request:{id:bill.request_id},context:{pm:{id:bill.property_manager_id}},stripe:{}}),/already been paid/);},async(_u,o={})=>reply([{...bill,status:'paid',...(o.body?JSON.parse(o.body):{})}])));
test('cross-origin and invalid capability are rejected before database/Stripe',async()=>{assert.equal((await run({},undefined,{origin:'https://evil.example'})).status,403);assert.equal((await run({token:'bad'})).status,400);});
test('signed Stripe webhook settles guest bill and sends receipt only to manager',()=>mocked(async()=>{
 const Stripe=require('stripe');const webhook=require('../api/stripe-webhook.js');const {Readable}=require('node:stream');
 const prevKey=process.env.STRIPE_SECRET_KEY,prevSecret=process.env.STRIPE_WEBHOOK_SECRET;process.env.STRIPE_SECRET_KEY='sk_test_mock';process.env.STRIPE_WEBHOOK_SECRET='whsec_mock';
 try{const payload=JSON.stringify({id:'evt_mock',type:'checkout.session.completed',data:{object:paid}});const signature=Stripe.webhooks.generateTestHeaderString({payload,secret:'whsec_mock'});const req=Readable.from([Buffer.from(payload)]);req.method='POST';req.headers={'stripe-signature':signature};const result={};const res={status(c){result.status=c;return this;},json(d){result.data=d;},send(d){result.data=d;}};await webhook(req,res);assert.equal(result.status,200);assert.equal(result.data.handled,true);}finally{if(prevKey===undefined)delete process.env.STRIPE_SECRET_KEY;else process.env.STRIPE_SECRET_KEY=prevKey;if(prevSecret===undefined)delete process.env.STRIPE_WEBHOOK_SECRET;else process.env.STRIPE_WEBHOOK_SECRET=prevSecret;}
},async(u,o={})=>{if(u.includes('pm_guest_bills?'))return reply([{...bill,stripe_session_id:paid.id}]);if(u.endsWith('/rpc/record_pm_guest_bill_payment'))return reply({duplicate:false});if(u==='https://api.resend.com/emails'){const mail=JSON.parse(o.body);assert.deepEqual(mail.to,['manager@example.com']);assert.equal(mail.reply_to,'info@dryerdudes.com');assert.equal(o.headers['Idempotency-Key'],'guest-bill-paid/cs_test_guest');return reply({id:'email'});}throw Error(u);}));

test('completion receipt preserves zero collected and does not count Full Service twice',()=>{
 const fs=require('node:fs'),vm=require('node:vm');const source=fs.readFileSync(require.resolve('../api/tech-complete-booking.js'),'utf8');const start=source.indexOf('function finalReceiptMath('),end=source.indexOf('function buildFinalReceiptHtml(',start);const math=vm.runInNewContext(source.slice(start,end)+';finalReceiptMath');const result=math({booking:{base_fee_cents:8000,full_service_cents:2000,collected_cents:0},billing:{total_job_cents:10000,parts_cost_cents:0,add_full_service_cents:2000,amount_already_collected_cents:0,payment_status:'not_sent'}});assert.equal(result.totalPaidCents,0);assert.equal(result.remainingBalanceCents,10000);assert.equal(result.fullServiceCents,2000);
});
